### PR TITLE
feat(ui): improve accessibility

### PR DESCRIPTION
**Pull request by dvalleri**
improve accessibility

### CODE REVIEW

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Review by lucataglia — APPROVED** [review]

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Pull request merged**
