### PR TITLE
feat(ui): add dark mode

### PR DESCRIPTION
**Pull request by dvalleri**
Implementations:
- add new button to switch dark/light mode
- fix color label and other minor fixies
- update version of design system

### CODE REVIEW

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Comment by devops-radicalbit** [comment]
### No vulnerabilities detected
No vulnerabilities with HIGH,CRITICAL severity have been detected in the code.

**Review by lucataglia — APPROVED** [review]

**Pull request merged**
